title: RDB's blog
author: Rob de Boer
email: rob@deboer.com
description: > # this means to ignore newlines until "baseurl:"
  I am learning how to use Github Pages for a blog

# social links
twitter_username: rob # DO NOT include the @ character, or else the build will fail!
github_username:  roblkdeboer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
